name: WASM Build + Deploy

on: [ push ]

jobs:
  qmc2-rust-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1

      - name: ğŸ“¦ Install dependencies
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: ğŸ”§ Produce WASM build
        run: |
          bash qmc2-wasm/build.sh --build

      - name: ğŸš€ Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public
